services:
  - name: web
    buildCommand: npm install
    startCommand: npm start
    env:
      - key: NODE_ENV
        value: production
    ports:
      - port: 5000
        protocol: http
      - port: 8080
        protocol: tcp
